language: node_js
node_js: 12
env:
  global:
    - NODE_ENV=testing
stages: test

jobs:
  include:
    - stage: test
      before_script: npm i -g @adonisjs/cli
      script: touch .env 
      script: adonis test 